name: curl
version: "8.11.1"
description: "HTTPS-enabled HTTP client"
category: "utility"
build:
  type: "source"
  url: "https://curl.se/download/curl-{version}.tar.gz"
  configure_flags:
    - "--disable-shared"
    - "--enable-static"
    - "--disable-ldap"
    - "--disable-ipv6"
    - "--with-openssl"
    - "--with-zlib"
    - "--disable-docs"
    - "--disable-manual"
    - "--without-libpsl"
    - "--with-ca-bundle=/etc/ssl/certs/ca-certificates.crt"
  build_dependencies:
    - "build-essential"
    - "libssl-dev"
    - "zlib1g-dev"
    - "wget"
    - "ca-certificates"
    - "pkg-config"
  runtime_libraries:
    - "/lib/x86_64-linux-gnu/libssl.so.3"
    - "/lib/x86_64-linux-gnu/libcrypto.so.3"
    - "/lib/x86_64-linux-gnu/libz.so.1"
    - "/usr/lib/x86_64-linux-gnu/libzstd.so.1"
  binary_path: "/tmp/curl"
  install_path: "/usr/local/bin/curl"
  test_command: "curl --version"