name: git
version: "2.50.1"
description: "Version control system"
category: "development"
build:
  type: "source"
  url: "https://github.com/git/git/archive/v{version}.tar.gz"
  configure_flags:
    - "--prefix=/tmp/git-install"
    - "--with-curl"
    - "--with-expat"
    - "--with-openssl"
    - "--without-tcltk"
    - "--without-python"
  custom_build_steps:
    - "make configure"
  build_dependencies:
    - "build-essential"
    - "libssl-dev"
    - "libghc-zlib-dev"
    - "libcurl4-gnutls-dev"
    - "libpcre2-dev"
    - "liblzma-dev"
    - "libexpat1-dev"
    - "gettext"
    - "unzip"
    - "wget"
    - "ca-certificates"
    - "binutils"
    - "autoconf"
    - "make"
  runtime_libraries:
    - "/lib/x86_64-linux-gnu/libpcre2-8.so.0"
    - "/lib/x86_64-linux-gnu/libz.so.1"
  binary_path: "/tmp/git-install"
  install_path: "/usr/local/"
  test_command: "git --version"