name: git
version: "2.50.1"
description: "Version control system"
category: "development"
build:
  type: "source"
  url: "https://github.com/git/git/archive/v{version}.tar.gz"
  configure_flags:
    - "--prefix=/tmp/git-install"
    - "--with-curl"
    - "--with-expat"
    - "--with-openssl"
    - "--without-tcltk"
    - "--without-python"
  build_dependencies:
    - "build-essential"
    - "libssl-dev"
    - "libghc-zlib-dev"
    - "libcurl4-gnutls-dev"
    - "libpcre2-dev"
    - "liblzma-dev"
    - "libexpat1-dev"
    - "gettext"
    - "unzip"
    - "wget"
    - "ca-certificates"
    - "binutils"
    - "autoconf"
    - "make"
  runtime_libraries:
    - "/usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4"
    - "/usr/lib/x86_64-linux-gnu/libpcre2-8.so.0"
    - "/lib/x86_64-linux-gnu/liblzma.so.5"
    - "/usr/lib/x86_64-linux-gnu/libexpat.so.1"
    - "/usr/lib/x86_64-linux-gnu/libgnutls.so.30"
    - "/usr/lib/x86_64-linux-gnu/libhogweed.so.6"
    - "/usr/lib/x86_64-linux-gnu/libnettle.so.8"
    - "/usr/lib/x86_64-linux-gnu/libgmp.so.10"
    - "/usr/lib/x86_64-linux-gnu/libidn2.so.0"
    - "/usr/lib/x86_64-linux-gnu/libunistring.so.5"
    - "/usr/lib/x86_64-linux-gnu/libtasn1.so.6"
    - "/usr/lib/x86_64-linux-gnu/libp11-kit.so.0"
    - "/usr/lib/x86_64-linux-gnu/libffi.so.8"
  binary_path: "/tmp/git-install"
  install_path: "/usr/local/"
  test_command: "git --version"