name: jq
version: "1.7.1"
description: "JSON processor"
category: "utility"
build:
  type: "download"
  url: "https://github.com/jqlang/jq/releases/download/v{version}/jq-linux-amd64"
  build_dependencies:
    - "wget"
    - "ca-certificates"
    - "binutils"
  runtime_libraries: []
  binary_path: "/tmp/jq"
  install_path: "/usr/local/bin/jq"
  test_command: "jq --version"