name: postgres
version: "17.2"
description: "PostgreSQL database server with complete toolset"
category: "database"
build:
  type: "source"
  url: "https://ftp.postgresql.org/pub/source/v{version}/postgresql-{version}.tar.bz2"
  configure_flags:
    - "--prefix=/tmp/postgres-install"
    - "--with-openssl"
    - "--with-readline"
    - "--with-zlib"
    - "--with-lz4"
    - "--with-zstd"
    - "--with-icu"
    - "--with-libxml"
    - "--with-pam"
    - "--with-gssapi"
    - "--with-ldap"
    - "--enable-thread-safety"
  build_dependencies:
    - "build-essential"
    - "bzip2"
    - "wget"
    - "ca-certificates"
    - "libssl-dev"
    - "zlib1g-dev"
    - "libreadline-dev"
    - "libxml2-dev"
    - "libxslt1-dev"
    - "libicu-dev"
    - "liblz4-dev"
    - "libzstd-dev"
    - "libpam0g-dev"
    - "libkrb5-dev"
    - "libldap2-dev"
    - "libsasl2-dev"
    - "uuid-dev"
    - "pkg-config"
  runtime_libraries:
    # Core system libraries
    - "/lib/x86_64-linux-gnu/libm.so.6"
    - "/lib/x86_64-linux-gnu/libdl.so.2"
    - "/lib/x86_64-linux-gnu/librt.so.1"
    # Security libraries
    - "/lib/x86_64-linux-gnu/libssl.so.3"
    - "/lib/x86_64-linux-gnu/libcrypto.so.3"
    - "/lib/x86_64-linux-gnu/libpam.so.0"
    # Kerberos libraries
    - "/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2"
    - "/usr/lib/x86_64-linux-gnu/libkrb5.so.3"
    - "/usr/lib/x86_64-linux-gnu/libk5crypto.so.3"
    - "/usr/lib/x86_64-linux-gnu/libcom_err.so.2"
    - "/usr/lib/x86_64-linux-gnu/libkrb5support.so.0"
    # Compression libraries
    - "/lib/x86_64-linux-gnu/libz.so.1"
    - "/usr/lib/x86_64-linux-gnu/libzstd.so.1"
    - "/usr/lib/x86_64-linux-gnu/liblz4.so.1"
    - "/lib/x86_64-linux-gnu/liblzma.so.5"
    # Unicode/XML libraries
    - "/usr/lib/x86_64-linux-gnu/libicudata.so.74"
    - "/usr/lib/x86_64-linux-gnu/libicui18n.so.74"
    - "/usr/lib/x86_64-linux-gnu/libicuuc.so.74"
    - "/usr/lib/x86_64-linux-gnu/libxml2.so.2"
    - "/usr/lib/x86_64-linux-gnu/libxslt.so.1"
    # LDAP libraries
    - "/usr/lib/x86_64-linux-gnu/libldap.so.2"
    - "/usr/lib/x86_64-linux-gnu/liblber.so.2"
    - "/usr/lib/x86_64-linux-gnu/libsasl2.so.2"
    # Terminal libraries
    - "/usr/lib/x86_64-linux-gnu/libreadline.so.8"
    - "/usr/lib/x86_64-linux-gnu/libtinfo.so.6"
    # Additional dependencies
    - "/lib/x86_64-linux-gnu/libuuid.so.1"
    - "/usr/lib/x86_64-linux-gnu/libgnutls.so.30"
    - "/usr/lib/x86_64-linux-gnu/libhogweed.so.6"
    - "/usr/lib/x86_64-linux-gnu/libnettle.so.8"
    - "/usr/lib/x86_64-linux-gnu/libgmp.so.10"
    - "/usr/lib/x86_64-linux-gnu/libidn2.so.0"
    - "/usr/lib/x86_64-linux-gnu/libunistring.so.5"
    - "/usr/lib/x86_64-linux-gnu/libtasn1.so.6"
    - "/usr/lib/x86_64-linux-gnu/libp11-kit.so.0"
    - "/usr/lib/x86_64-linux-gnu/libffi.so.8"
    - "/usr/lib/x86_64-linux-gnu/libkeyutils.so.1"
  binary_path: "/tmp/postgres-install"
  install_path: "/usr/local/"
  test_command: "postgres --version"