name: postgres
version: "17.5"
description: "PostgreSQL with sensible defaults (postgres/postgres/postgres)"
category: "database"
build:
  test_command: "postgres --version"
defaults:
  user: "postgres"
  password: "postgres"
  database: "postgres"
  data_dir: "/var/lib/postgresql/data"
  port: 5432