# Docker Compose for backrest distroless stack
name: "backrest"

services:
  backrest-app:
    container_name: "${COMPOSE_PROJECT_NAME:-backrest}-app"
    image: distroless-backrest:1.9.1
    ports:
      - "${WEB_PORT:-9898}:9898"
    environment:
      BACKREST_PORT: "${BACKREST_PORT:-0.0.0.0:9898}"
      BACKREST_DATA: "/var/lib/backrest/data"
      BACKREST_CONFIG: "/etc/backrest/config.json"
      XDG_CACHE_HOME: "/var/cache/backrest"
      TMPDIR: "/tmp"
      TZ: "${TZ:-UTC}"
      BACKREST_RESTIC_COMMAND: "/usr/local/bin/restic"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
    volumes:
      - backrest_data:/var/lib/backrest/data
      - backrest_config:/etc/backrest
      - backrest_cache:/var/cache/backrest
      - "${BACKUP_SOURCE_PATH:-./data}:/userdata:ro"
      - backrest_repos:/repos
    restart: unless-stopped
    read_only: true
    tmpfs:
      - "/tmp:size=${TMPFS_SIZE:-2G},noexec,nosuid,nodev"

volumes:
  backrest_data:
  backrest_config:
  backrest_cache:
  backrest_repos: