# Nginx Service - supports both build and image deployment modes
#
# Usage:
#   Build from source:     docker compose --profile build up
#   Deploy from image:     docker compose --profile image up
#   Default (build mode):  docker compose up

services:
  # Build from source (default)
  nginx:
    profiles: ["build", ""]
    build:
      context: ..
      dockerfile: nginx/Dockerfile
      args:
        APP_UID: ${APP_UID:-1000}
        APP_GID: ${APP_GID:-1000}
        TZ: ${TZ:-UTC}
    image: distroless-nginx:1.29.1
    container_name: distroless-nginx
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "${NGINX_HTTP_PORT:-8080}:8080"
      - "${NGINX_HTTPS_PORT:-8443}:8443"
      - "${NGINX_QUIC_PORT:-8443}:8443/udp"
    volumes:
      - nginx-html:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "-t", "-q"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=50m
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  # Deploy from pre-built image
  nginx-image:
    profiles: ["image"]
    image: ghcr.io/cougz/awesome-distroless/nginx:1.29.1
    container_name: distroless-nginx
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "${NGINX_HTTP_PORT:-8080}:8080"
      - "${NGINX_HTTPS_PORT:-8443}:8443"
      - "${NGINX_QUIC_PORT:-8443}:8443/udp"
    volumes:
      - nginx-html:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "-t", "-q"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=50m
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  nginx-html: