services:
  nginx:
    build:
      context: ..
      dockerfile: nginx/Dockerfile
    image: nginx-quic
    container_name: distroless-nginx
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "${NGINX_HTTP_PORT:-8080}:8080"
      - "${NGINX_HTTPS_PORT:-8443}:8443"
      - "${NGINX_QUIC_PORT:-8443}:8443/udp"
    volumes:
      - nginx-html:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "/usr/local/bin/nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=50m
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  nginx-html: