services:
  nginx:
    build:
      context: ..
      dockerfile: nginx/Dockerfile
    image: distroless-nginx:1.27.3
    container_name: distroless-nginx
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "${NGINX_PORT:-8080}:8080"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./config:/etc/nginx/conf.d:ro
    healthcheck:
      test: ["CMD", "/usr/local/bin/nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    tmpfs:
      - /tmp:noexec,nosuid,size=50m
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL