services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-1.0.0}
        APP_UID: ${APP_UID:-1000}
        APP_GID: ${APP_GID:-1000}
        TZ: ${TZ:-UTC}
    image: distroless-base:${VERSION:-1.0.0}
    container_name: distroless-base-test
    command: ["sleep", "1"]