services:
  postgres:
    build:
      context: ..
      dockerfile: postgres/Dockerfile
    image: distroless-postgres:17.5
    container_name: distroless-postgres
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "/usr/local/bin/pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /run:noexec,nosuid,size=10m
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  postgres-data: