version: '3.8'

services:
  postgres:
    build:
      context: ..
      dockerfile: postgres/Dockerfile
      args:
        VERSION: 17.5
        APP_UID: 1000
        APP_GID: 1000
        TZ: UTC
    image: distroless-postgres:17.5
    container_name: distroless-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      TZ: ${TZ:-UTC}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      # Bind mount for data persistence (no Docker volumes)
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "/usr/local/bin/pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    # Read-only root filesystem for security
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /run:noexec,nosuid,size=10m
    # Security settings
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M