# Redis Service - supports both build and image deployment modes
#
# Usage:
#   Build from source:     docker compose --profile build up
#   Deploy from image:     docker compose --profile image up
#   Default (build mode):  docker compose up

services:
  # Build from source (default)
  redis:
    profiles: ["build", ""]
    build:
      context: ..
      dockerfile: redis/Dockerfile
      args:
        APP_UID: ${APP_UID:-1000}
        APP_GID: ${APP_GID:-1000}
        TZ: ${TZ:-UTC}
    image: distroless-redis:7.4.2
    container_name: distroless-redis
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "/usr/local/bin/redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=10m
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  # Deploy from pre-built image
  redis-image:
    profiles: ["image"]
    image: ghcr.io/cougz/awesome-distroless/redis:7.4.2
    container_name: distroless-redis
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "/usr/local/bin/redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=10m
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  redis-data: